Remove unsupported initial_as_of from predtimechart config
Error: Additional properties are not allowed ('initial_as_of' was unexpected)

The predtimechart schema does not support 'initial_as_of' property.
Dashboard will automatically select the latest available date.

Supported properties:
- rounds_idx, reference_date_col_name, target_date_col_name
- horizon_col_name, initial_checked_models, disclaimer
- initial_xaxis_range, task_id_text, target_data_file_name